### ISSUE TITLE
UnicodeDecodeError:

### ISSUE THREAD

**Issue by phoenixindicus** [kkneomis/kc7#57]
Traceback (most recent call last):
  File "C:\cyber-challenger\app.py", line 1, in <module>
    from app import application
  File "C:\cyber-challenger\app\__init__.py", line 37, in <module>
    from app.server.views import main
  File "C:\cyber-challenger\app\server\views.py", line 18, in <module>
    from app.server.modules.logging.uploadLogs import LogUploader
  File "C:\cyber-challenger\app\server\modules\logging\uploadLogs.py", line 18, in <module>
    from app.server.modules.email.email import Email
  File "C:\cyber-challenger\app\server\modules\email\email.py", line 13, in <module>
    from app.server.modules.actors.Actor import Actor
  File "C:\cyber-challenger\app\server\modules\actors\Actor.py", line 19, in <module>
    sentenceGenerator = SentenceGenerator()
  File "C:\cyber-challenger\app\server\modules\helpers\markov_sentence_generator.py", line 14, in __init__
    self.load_words()
  File "C:\cyber-challenger\app\server\modules\helpers\markov_sentence_generator.py", line 42, in load_words
    response = f.read()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 8315: character maps to <undefined>

This isssue is fixed when you use encoding='utf8' in open function - 
def load_words(self):
        """
        Load a list of words from a given text url
        """
        if "http" in self.word_source:
            response = requests.get(self.word_source).text
        else:
            with open(self.word_source , encoding='utf8') as f:
                response = f.read()

        # remove unwanted characters
        table = str.maketrans(dict.fromkeys('#<>-'))
        response = response.translate(table)

**Comment by gregs1998** [comment]
This is resolved in latest refactor of SentenceGenerator

#83
